export {default as categorySlice} from './category/categorySlice'
export {default as slideSlice} from './homeslide/slideSlice'
export {default as subCategory} from './subcategory/subCategorySlice'
export {default as productSlice} from './product/productSlice'
export {default as productType} from './productType/productTypeSclie'
export {default as supImage} from './supimageslice/supportImageSlice'
export {default as authSlice} from './auth/authSlice'
